---
title: "Outlier Odds"
execute:
  echo: false
  message: false
  warning: false
author: "James Brown"
date: "2024-03-12"
format:
  html:
    df-print: kable
    max-width: 100%
    theme: cosmo
    self-contained: true
    toc: true
    toc-depth: 3
    fig-width: 8
    fig-height: 6
editor: source
---

```{r setup, include=FALSE}
library(tidyverse)
library(qreport)
library(DT)

# Load data
  h2h_data <- read_rds("../Data/processed_odds/all_h2h.rds")
  line_data <- read_rds("../Data/processed_odds/all_line.rds")
  player_disposals_data <- read_rds("../Data/processed_odds/all_player_disposals.rds")
  player_goals_data <- read_rds("../Data/processed_odds/all_player_goals.rds")
  player_fantasy_data <- read_rds("../Data/processed_odds/all_player_fantasy_points.rds")
```

```{r}
# Get all markets together
  all_markets <- bind_rows(
    player_disposals_data,
    player_goals_data,
    player_fantasy_data
  )

# Arrange in order
all_markets <-
all_markets |>
  select(
    match,
    player_name,
    player_team,
    opposition_team,
    market_name,
    over_price,
    implied_prob_over,
    under_price,
    implied_prob_under,
    line,
    agency,
    diff_over_2023,
    diff_over_last_10,
    diff_under_2023
  ) |>
  arrange(match, player_name, market_name, line, desc(over_price))
```

```{r}
# Get biggest differences from second best odds available
  biggest_diffs <-
  all_markets |>
    group_by(match, player_name, market_name, line) |> 
    distinct(match, player_name, market_name, line, agency, .keep_all = TRUE) |> 
    mutate(number_of_odds = n()) |>
    mutate(best_implied_prob_over = implied_prob_over,
           second_best_implied_prob_over = lead(implied_prob_over, 1),
           second_best_odds = lead(over_price, 1)) |>
  slice_head(n = 1) |> 
  ungroup() |> 
  filter(number_of_odds > 1) |>
  mutate(diff_over = second_best_implied_prob_over - best_implied_prob_over) |>
  select(-number_of_odds, -best_implied_prob_over, -second_best_implied_prob_over) |>
  arrange(desc(diff_over), match, player_name, market_name, line) |> 
  relocate(second_best_odds, .after = over_price)
```

# Biggest Outliers By Agency

```{r}
#| results: asis

# Outlier List
biggest_diffs_outliers <-
  biggest_diffs |>
  filter(diff_over >= 0.03) |> 
  arrange(desc(diff_over_last_10)) |> 
  rename(gap = diff_over) 

# Function to take list, filter to agency and return
filter_agency <- function(df, agency) {
  df |>
    filter(agency == !!agency)
}

# Unique list of agencies
agencies <- biggest_diffs_outliers$agency |> unique()

# Make list of dataframes
agency_list <- map(agencies, ~filter_agency(biggest_diffs_outliers, .x)) |> set_names(agencies)

# # For each element of the list, make a DT table
# agency_list <-
#   map(agency_list, ~ datatable(.x, options = list(
#     pageLength = 10, scrollX = TRUE, width = "100%"
#   )))

# Make tabset with each team's CBAs
maketabs(agency_list, wide = TRUE)
```
