---
title: "Cuzzy's Scale of Hardness"
execute:
  echo: false
  message: false
  warning: false
author: "James Brown"
date: "`r Sys.Date()`"
format:
  html:
    df-print: kable
    theme: cosmo
    self-contained: true
    toc: true
    toc-depth: 3
    fig-width: 8
    fig-height: 6
editor: visual
---

```{r}
library(tidyverse)

# Read in data
dvp_data <- read_csv("dvp_data.csv")

# Make Pos a factor with order
dvp_data$Pos <-
  factor(
    dvp_data$Pos,
    levels = c(
      "Key Defender",
      "Small Defender",
      "Offensive Defender",
      "CBA < 50%",
      "CBA > 50%",
      "Wing",
      "Ruck",
      "Small Forward",
      "Key Forward"
    ), ordered = TRUE)

disposals_dvp <- 
  dvp_data |> 
  filter(market_name == "Player Disposals")

marks_dvp <- 
  dvp_data |> 
  filter(market_name == "Player Marks")

tackles_dvp <- 
  dvp_data |> 
  filter(market_name == "Player Tackles")

fantasy_points_dvp <-
  dvp_data |> 
  filter(market_name == "Player Fantasy Points")

goals_dvp <-
  dvp_data |> 
  filter(market_name == "Player Goals")

```

::: panel-tabset
### Disposals

```{r}
# Create disposals heatmap
  disposals_dvp |> 
  ggplot(aes(x = Pos, y = Opponent, fill = dvp)) +
  geom_tile() +
  scale_fill_gradient2(low = "red", mid = "white", high = "green", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = NULL, title = "Player Disposals") +
  geom_text(aes(label = round(dvp, 1)), size = 3)

```

### Marks

```{r}
# Create marks heatmap
  marks_dvp |> 
  ggplot(aes(x = Pos, y = Opponent, fill = dvp)) +
  geom_tile() +
  scale_fill_gradient2(low = "red", mid = "white", high = "green", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = NULL, title = "Player Marks") +
  geom_text(aes(label = round(dvp, 1)), size = 3)

```

### Tackles

```{r}
# Create tackles heatmap
  tackles_dvp |> 
  ggplot(aes(x = Pos, y = Opponent, fill = dvp)) +
  geom_tile() +
  scale_fill_gradient2(low = "red", mid = "white", high = "green", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = NULL, title = "Player Tackles") +
  geom_text(aes(label = round(dvp, 1)), size = 3)

```

### Fantasy Points

```{r}
# Create fantasy_points heatmap
  fantasy_points_dvp |> 
  ggplot(aes(x = Pos, y = Opponent, fill = dvp)) +
  geom_tile() +
  scale_fill_gradient2(low = "red", mid = "white", high = "green", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = NULL, title = "Player Fantasy Points") +
  geom_text(aes(label = round(dvp, 1)), size = 3)

```

### Goals

```{r}
# Create goals heatmap
  goals_dvp |> 
  ggplot(aes(x = Pos, y = Opponent, fill = dvp)) +
  geom_tile() +
  scale_fill_gradient2(low = "red", mid = "white", high = "green", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = NULL, title = "Player Goals") +
  geom_text(aes(label = round(dvp, 1)), size = 3)

```

:::
